### ISSUE TITLE
Problem with empty Key

### ISSUE THREAD

**Issue by blackteck** [ddast/bibf#5]
When the key is left empty (e.g. from journal exports) bibf takes "\n firstField = firstvalue" as the key, deleting the field when creating a new key.

Suggestion: Clean Key from "\n", " ", "\t" and search for illegal characters like "=". If Key is illegal exit and give a useful error message like the linenumber, the wrong key or the complete corrupted entry.

**Comment by ddast** [comment]
Fixed in 0dab4054c2888a0cc248f3ae8fa09d70255f02b8
